### ISSUE TITLE
感谢整理 面试题答案

### ISSUE THREAD

**Issue by AweiLoveAndroid** [DthFish/ScrollViewIndicator#1]
感谢整理 面试题答案  如果整理好了 可以pull request的

**Comment by DthFish** [comment]
嗯，会的，整理的也不是很准确，最终还是需要大家一起查漏补缺^_^


| |
DthFIsh
邮箱：dthfish@163.com
|

在2018年03月06日 01:18，阿韦 写道：

感谢整理 面试题答案 如果整理好了 可以pull request的
